/*
You are given two strings s and t.
String t is generated by random shuffling string s and then add one more letter at a random position.
Return the letter that was added to t.
*/

#include <bits/stdc++.h>
using namespace std;

char findTheDifference(string s, string t)
{
    int n1 = 0, n2 = 0;
    for (int i = 0; i < s.length(); i++)
    {
        n1 += (int)s[i];
    }
    for (int i = 0; i < t.length(); i++)
    {
        n2 += (int)t[i];
    }
    return (char)(n2 - n1);
}

int main()
{
    string s = "abcd", t = "abcde";
    cout << findTheDifference(s, t);
    return 0;
}